### ISSUE TITLE
Unable to locate DLL file (77218953)

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#151]
> This issue was submitted by the add-in's exception handler.
#### Exception:

``` csharp
Bovender.Unmanaged.DllNotFoundException: Unable to locate DLL file
   at Bovender.Unmanaged.DllManager.LoadDll(String dllName, String expectedSha1Hash)
   at Bovender.Unmanaged.DllManager.LoadDll(String dllName)
   at XLToolbox.Export.Exporter..ctor()
   at XLToolbox.Export.Exporter..ctor(SingleExportSettings settings)
   at XLToolbox.Export.ViewModels.SingleExportSettingsViewModel..ctor(SingleExportSettings singleExportSettings)
   at XLToolbox.Dispatcher.ExportSelection()
   at XLToolbox.Dispatcher.Execute(Command cmd)
```

Message: Unable to locate DLL file
#### Environment

| Parameter | Value |
| --- | --- |
| Version | 7.0.5 |
| OS | Microsoft Windows NT 6.1.7601 Service Pack 1, 64-bit |
| Excel | 2013 SP1 (15.0.4833), 32-bit |
| CLR | 4.0.30319.42000, 32-bit |
| VSTO runtime | 10.0.40820 |
| ClickOnce | True |
| Bovender | 0.11.3.0 |
| FreeImage | Unable to locate DLL file |

**Comment by bovender** [comment]
The submitted information indicates that the add-in was installed using the 'ClickOnce' mechanism, e.g. by double-clicking the .vsto file in the installation directory. This is not the proper way to install the add-in. If the installer failed to active the add-in in Excel, some users have reverted to double-clicking the .vsto file. It would be interesting to know what went wrong during installation.

If the add-in is installed using the 'ClickOnce' mechanism, the required DLL files are not installed.
