### ISSUE TITLE
Could not find file 'C:\Users\process-11\Desktop\XLToolbox-7.1.3.exe'. (78283b3b)

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#182]
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
System.IO.FileNotFoundException: Could not find file 'C:\Users\process-11\Desktop\XLToolbox-7.1.3.exe'.
File name: 'C:\Users\process-11\Desktop\XLToolbox-7.1.3.exe'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Bovender.FileHelpers.Sha256Hash(String file)
   at Bovender.Versioning.Updater.Verify()
   at Bovender.Versioning.Updater.Install()
   at Bovender.Versioning.UpdaterViewModel.Install(Object param)
   at Bovender.Mvvm.DelegatingCommand.Execute(Object parameter)
````

Message: Could not find file 'C:\Users\process-11\Desktop\XLToolbox-7.1.3.exe'.
#### Environment

Parameter    | Value
-------------|------
Version      | 7.1.2
OS           | Microsoft Windows NT 6.2.9200.0, 32-bit
Excel        | 2010 SP2 (14.0.7172), 32-bit
CLR          | 4.0.30319.42000, 32-bit
VSTO runtime | 10.0.40305
ClickOnce    | False
Bovender     | 0.14.5.0
FreeImage    | 3.16.0

**Comment by bovender** [comment]
Maybe fixed by 1a6efbe273ad30a5317dca2ffc800e02fa7ce306 (unless the user who submitted the report had moved the downloaded file somewhere else).
