### ISSUE TITLE
Cannot run the macro 'RuneWatermark'. The macro may not be available in this workbook or all macros may be disabled. (7470428b)

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#31]
> This issue was submitted by the add-ins's exception handler.

#### Exception:

````csharp
System.Runtime.InteropServices.COMException (0x800A03EC): Cannot run the macro 'RuneWatermark'. The macro may not be available in this workbook or all macros may be disabled.
   at Microsoft.Office.Interop.Excel._Application.Run(Object Macro, Object Arg1, Object Arg2, Object Arg3, Object Arg4, Object Arg5, Object Arg6, Object Arg7, Object Arg8, Object Arg9, Object Arg10, Object Arg11, Object Arg12, Object Arg13, Object Arg14, Object Arg15, Object Arg16, Object Arg17, Object Arg18, Object Arg19, Object Arg20, Object Arg21, Object Arg22, Object Arg23, Object Arg24, Object Arg25, Object Arg26, Object Arg27, Object Arg28, Object Arg29, Object Arg30)
   at XLToolbox.Legacy.LegacyToolbox.RunCommand(Command command) in XLToolbox\Legacy\LegacyToolbox.cs:line 195
   at XLToolbox.Dispatcher.Execute(Command cmd) in XLToolbox\Dispatcher.cs:line 107
````

Message: Cannot run the macro 'RuneWatermark'. The macro may not be available in this workbook or all macros may be disabled.

**Comment by bovender** [comment]
Closed by d80c47d944f4a3908452c12ff2875bd4c746dbba.
