### ISSUE TITLE
无法运行“RunChartDesign”宏。可能是因为该宏在此工作簿中不可用，或者所有的宏都被禁用。

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#616]
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
System.Runtime.InteropServices.COMException (0x800A03EC): 无法运行“RunChartDesign”宏。可能是因为该宏在此工作簿中不可用，或者所有的宏都被禁用。
   at Microsoft.Office.Interop.Excel._Application.Run(Object Macro, Object Arg1, Object Arg2, Object Arg3, Object Arg4, Object Arg5, Object Arg6, Object Arg7, Object Arg8, Object Arg9, Object Arg10, Object Arg11, Object Arg12, Object Arg13, Object Arg14, Object Arg15, Object Arg16, Object Arg17, Object Arg18, Object Arg19, Object Arg20, Object Arg21, Object Arg22, Object Arg23, Object Arg24, Object Arg25, Object Arg26, Object Arg27, Object Arg28, Object Arg29, Object Arg30)
   at XLToolbox.Legacy.LegacyToolbox.RunCommand(Command command) in XLToolbox\Legacy\LegacyToolbox.cs:line 198
   at XLToolbox.Dispatcher.Execute(Command cmd) in XLToolbox\Dispatcher.cs:line 83
````

Message: 无法运行“RunChartDesign”宏。可能是因为该宏在此工作簿中不可用，或者所有的宏都被禁用。
#### Environment

Parameter    | Value
-------------|------
Version      | 7.2.12
OS           | Microsoft Windows NT 10.0.15063.0, 64-bit
Excel        | 365 (16.0.8326), 64-bit
CLR          | 4.0.30319.42000, 64-bit
VSTO runtime | 10.0.60301
ClickOnce    | False
Bovender     | 0.17.0.0
FreeImage    | 3.16.0
Identifier   | 18acbac4ba7981f39a556f8013e5151856f654b67e3cc940b468b91056a0861e

**Comment by bovender** [comment]
### Another report
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
System.Runtime.InteropServices.COMException (0x800A03EC): 无法运行“RunChartDesign”宏。可能是因为该宏在此工作簿中不可用，或者所有的宏都被禁用。
   at Microsoft.Office.Interop.Excel._Application.Run(Object Macro, Object Arg1, Object Arg2, Object Arg3, Object Arg4, Object Arg5, Object Arg6, Object Arg7, Object Arg8, Object Arg9, Object Arg10, Object Arg11, Object Arg12, Object Arg13, Object Arg14, Object Arg15, Object Arg16, Object Arg17, Object Arg18, Object Arg19, Object Arg20, Object Arg21, Object Arg22, Object Arg23, Object Arg24, Object Arg25, Object Arg26, Object Arg27, Object Arg28, Object Arg29, Object Arg30)
   at XLToolbox.Legacy.LegacyToolbox.RunCommand(Command command) in XLToolbox\Legacy\LegacyToolbox.cs:line 198
   at XLToolbox.Dispatcher.Execute(Command cmd) in XLToolbox\Dispatcher.cs:line 83
````

Message: 无法运行“RunChartDesign”宏。可能是因为该宏在此工作簿中不可用，或者所有的宏都被禁用。
#### User comment on submission:

1
#### Environment

Parameter    | Value
-------------|------
Version      | 7.2.13
OS           | Microsoft Windows NT 6.1.7601 Service Pack 1, 64-bit
Excel        | 2010 (14.0.4756), 32-bit
CLR          | 4.0.30319.34209, 32-bit
VSTO runtime | 10.0.21022
ClickOnce    | False
Bovender     | 0.17.0.0
FreeImage    | 3.16.0
Identifier   | 18acbac4ba7981f39a556f8013e5151856f654b67e3cc940b468b91056a0861e
