### ISSUE TITLE
Invalid URI in ReleaseInfoViewModel

### ISSUE THREAD

**Issue by bblodfon** [bovender/XLToolbox#724]
Hi, when I open any excel document, the add-in takes some time to load. Enabling the logging, I saw this (don't know if it is related though):
```
2018-11-23 16:14:54.3183|INFO|Bovender.Versioning.ReleaseInfo|WebClient_DownloadStringCompleted: Status: FailureToParse
2018-11-23 16:14:54.3406|WARN|Bovender.Versioning.ReleaseInfoViewModel|SendProcessFinishedMessage: Exception occurred!
2018-11-23 16:14:54.3798|WARN|Bovender.Versioning.ReleaseInfoViewModel|System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Bovender.Versioning.ReleaseInfo.Parse(String rawInfo)
2018-11-23 16:14:54.3798|INFO|Bovender.Mvvm.Messaging.Message`1|Sending message to 1 subscriber(s)
2018-11-23 16:14:54.3798|DEBUG|Bovender.Mvvm.Messaging.Message`1|Message content is a Bovender.Mvvm.Messaging.ProcessMessageContent
2018-11-23 16:14:54.3952|WARN|XLToolbox.Versioning.ReleaseInfoViewModel|Exception during update check
2018-11-23 16:14:54.3952|WARN|XLToolbox.Versioning.ReleaseInfoViewModel|System.UriFormatException: Invalid URI: The URI scheme is not valid.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Bovender.Versioning.ReleaseInfo.Parse(String rawInfo)
2018-11-23 16:14:54.3952|INFO|Bovender.Mvvm.ViewModels.ProcessViewModelBase|SendProcessFinishedMessage: Sending message
2018-11-23 16:14:54.3952|INFO|Bovender.Mvvm.Messaging.Message`1|Sending message to 1 subscriber(s)
2018-11-23 16:14:54.3952|DEBUG|Bovender.Mvvm.Messaging.Message`1|Message content is a Bovender.Mvvm.Messaging.ProcessMessageContent
2018-11-23 16:14:54.9359|INFO|Bovender.Mvvm.ViewModels.ProcessViewModelBase|UpdateProgress: No longer processing, disposing update timer
```

**Comment by bovender** [comment]
The error is easy to explain, but it is definitively not the cause of any delays. When checking for a new version, the add-in downloads a text file that contains the current version and download URL. I had recently published an update, but while it worked well on my development machines, when I went to my work place and installed it, it would make Excel crash. So I stopped distributing the update after a few hours by adding invalid characters to the version information file. The error message was introduced by myself to be able to have a way to detect mistakes in the version information file, except that in this case the mistake was deliberate. Neither the text file download (which happens asynchronously) nor the error message can cause any delays.

Now for the actual question at hand: Why does it delay your start-up? I guess you have a situation where you start Excel and you see the splash screen with the notice "Loading XLToolboxForExcel..." and it seems to take forever, is that correct? If you have not done so yet, I would like to suggest to disable (not uninstall) the add-in (e.g. via File > Options > Add-ins > COM add-ins > Go, then clear the relevant check mark; or by enabling the Developer ribbon tab via File > Options > Customize ribbon, then placing a check mark in front of "Developer" in the right-hand list, which will make a new tab appear on the ribbon that contains a "COM add-ins" button). Disabling and re-enabling the add-in could confirm that it is indeed the Toolbox that delays startup.

Then, have a look at the time stamps in the entire Toolbox log file. They may be informative, but they might also be misleading, e.g. when a longer time span in that log simply indicates that the Toolbox was idle. But it depends, I would have to examine it closely. If you want, you could send me the entire file (for example to daniel at xltoolbox dot net, or via Telegram <https://t.me/bovender>).
