### ISSUE TITLE
COM object that has been separated from its underlying RCW cannot be used.

### ISSUE THREAD

**Issue by bovender** [bovender/XLToolbox#795]
### Another report
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.Dynamic.DynamicMetaObject.Create(Object value, Expression expression)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at XLToolbox.Excel.ViewModels.SheetViewModel.set_DisplayString(String value) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\SheetViewModel.cs:line 78
   at XLToolbox.Excel.ViewModels.WorkbookViewModel.ConfirmRenameSheet(StringMessageContent stringMessage) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\WorkbookViewModel.cs:line 669
   at XLToolbox.Excel.ViewModels.WorkbookViewModel.<DoRenameSheet>b__60_1(StringMessageContent stringMessage) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\WorkbookViewModel.cs:line 659
   at Bovender.Mvvm.Messaging.Message`1.<>c__DisplayClass3_0.<Send>b__0() in X:\Code\bovender\Bovender\Mvvm\Messaging\Message.cs:line 67
   at Bovender.Mvvm.Actions.MessageActionBase.<>c__DisplayClass5_1`1.<Invoke>b__0(Object sender, EventArgs e) in X:\Code\bovender\Bovender\Mvvm\Actions\MessageActionBase.cs:line 78
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Bovender.Mvvm.ViewModels.ViewModelBase.DoCloseView() in X:\Code\bovender\Bovender\Mvvm\ViewModels\ViewModelBase.cs:line 329
   at Bovender.Mvvm.Messaging.MessageContent.DoConfirm() in X:\Code\bovender\Bovender\Mvvm\Messaging\MessageContent.cs:line 84
   at Bovender.Mvvm.Messaging.MessageContent.<get_ConfirmCommand>b__21_0(Object param) in X:\Code\bovender\Bovender\Mvvm\Messaging\MessageContent.cs:line 55
   at Bovender.Mvvm.DelegatingCommand.Execute(Object parameter) in X:\Code\bovender\Bovender\Mvvm\DelegatingCommand.cs:line 121
````

Message: COM object that has been separated from its underlying RCW cannot be used.
#### Environment

Parameter    | Value
-------------|------
Version      | 7.3.4
OS           | Microsoft Windows NT 6.2.9200.0, 64-bit
Excel        | 2010 SP2 (14.0.7225), 32-bit
CLR          | 4.0.30319.42000, 32-bit
VSTO runtime | 10.0.40305
ClickOnce    | False
Bovender     | 0.18.0.0
FreeImage    | 3.18.0
Identifier   | b7ac8d4b50552c71a3d50b1e49d543f8609ee1c3486ad0d831029e030cca051d

**Comment by bovender** [comment]
### Another report
> This issue was submitted by the add-in's exception handler.

#### Exception:

````csharp
System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.Dynamic.DynamicMetaObject.Create(Object value, Expression expression)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at XLToolbox.Excel.ViewModels.SheetViewModel.set_DisplayString(String value) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\SheetViewModel.cs:line 78
   at XLToolbox.Excel.ViewModels.WorkbookViewModel.ConfirmRenameSheet(StringMessageContent stringMessage) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\WorkbookViewModel.cs:line 669
   at XLToolbox.Excel.ViewModels.WorkbookViewModel.<DoRenameSheet>b__60_1(StringMessageContent stringMessage) in X:\Code\xltoolbox\NG\XLToolbox\Excel\ViewModels\WorkbookViewModel.cs:line 659
   at Bovender.Mvvm.Messaging.Message`1.<>c__DisplayClass3_0.<Send>b__0() in X:\Code\bovender\Bovender\Mvvm\Messaging\Message.cs:line 67
   at Bovender.Mvvm.Actions.MessageActionBase.<>c__DisplayClass5_1`1.<Invoke>b__0(Object sender, EventArgs e) in X:\Code\bovender\Bovender\Mvvm\Actions\MessageActionBase.cs:line 78
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Bovender.Mvvm.ViewModels.ViewModelBase.DoCloseView() in X:\Code\bovender\Bovender\Mvvm\ViewModels\ViewModelBase.cs:line 329
   at Bovender.Mvvm.Messaging.MessageContent.DoConfirm() in X:\Code\bovender\Bovender\Mvvm\Messaging\MessageContent.cs:line 84
   at Bovender.Mvvm.Messaging.MessageContent.<get_ConfirmCommand>b__21_0(Object param) in X:\Code\bovender\Bovender\Mvvm\Messaging\MessageContent.cs:line 55
   at Bovender.Mvvm.DelegatingCommand.Execute(Object parameter) in X:\Code\bovender\Bovender\Mvvm\DelegatingCommand.cs:line 121
````

Message: COM object that has been separated from its underlying RCW cannot be used.
#### Environment

Parameter    | Value
-------------|------
Version      | 7.3.4
OS           | Microsoft Windows NT 6.2.9200.0, 64-bit
Excel        | 2010 SP2 (14.0.7225), 32-bit
CLR          | 4.0.30319.42000, 32-bit
VSTO runtime | 10.0.40305
ClickOnce    | False
Bovender     | 0.18.0.0
FreeImage    | 3.18.0
Identifier   | b7ac8d4b50552c71a3d50b1e49d543f8609ee1c3486ad0d831029e030cca051d
